---
title: "Council light response" #exploring light response, based on Kyle's Churchill code 
output: html_document
date: "2024-12-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())

library(ggplot2)
library(data.table)
library(openair)

#Read in Ameriflux HH data 

#original half-hourly dataframe 
df = fread('C:/Users/kkent/Documents/Council Data/Council BASE gapfilling/council_gapfilled_clean_2017_2023_for analysis.csv',na.strings = c('-9999','NA','NaN','NAN','-7999'))

summary(df$TIMESTAMP_END)

```


#calc NEE, sort by month, DOY, and yr 
```{r}
 #df$date = as.POSIXct(x = as.character(df$TIMESTAMP_END),format = '%Y%m%d%H%M',tz = 'UTC') --> already in this format 
#df = subset(df,df$date > as.POSIXct('2017-07-01'))
# df$dou

library(bigleaf)

#different averaging methods
library(dplyr)
df$month = format(df$date,'%m')
df$doy   = format(df$date,'%j')
df$year  = format(df$date,'%y')

#df$nee = df$FC_PI_F*60*30/1000000*12 #not sure what FC_PI_F is 

df$nee = df$FC_F*60*30/1000000*12
```



#Sums and avg for hh to daily 
```{r}
#sums of half hourly 
hh = df %>%
  group_by(year,month) %>%
  summarise(nee.h = sum(nee))

#daily means by month
dm = df %>%
  group_by(year,month,doy) %>%
  summarise(nee.av = mean(nee),
            one = 1) #why is this one here? 

dm$nee.daily = dm$nee.av*48 #why multiply by 48? 
```

#monthly
```{r}
dmo = dm %>%
  group_by(year,month) %>%
  summarise(nee.ave = mean(nee.daily),
            days = sum(one),
            nee.d = nee.ave*days,
            nee.daily.summed = sum(nee.daily))
```

#monthly means
```{r}
mo = df %>%
  group_by(year,month) %>%
  summarise(nee.av = mean(nee)*48)

mo$days = dmo$days
mo$nee.m = mo$days*mo$nee.av
```

#Plot to check, then merge 
```{r}
plot(dmo$nee.d,hh$nee.h)
plot(dmo$nee.d,mo$nee.m)



fin = merge(dmo,hh,by = c('month','year'),all = T)
fin = merge(fin,mo,by = c('month','year'),all = T)

#summary(lm())
```

```{r}
library(openair)

# date column was a character but wouldn't work with timeAverage - converted it to date and then it seems to work 

df$date <- as.Date(df$date)

av = timeAverage(mydata = df,avg.time = '1 day',data.thresh = 50,statistic = 'mean') #won't work 
#av <-timeAverage(df, avg.time = "day", data.thresh = 50)

gs = subset(av,av$TA > 5 & av$PPFD_IN > 0)
gs = gs[complete.cases(gs$PPFD_IN),]
gs = gs[complete.cases(gs$FC),]

gs = subset(df,df$TA > 8 & df$PPFD_IN > 0)
gs = gs[complete.cases(gs$PPFD_IN),]
gs = gs[complete.cases(gs$FC),]

lr = light.response(data = gs,NEE = 'FC',Reco = 'RECO',PPFD = 'PPFD_IN',PPFD_ref = 1500)
lr
fit = lr$m$fitted()
```


```{r}
ggplot(data = gs)+
  geom_point(aes(PPFD_IN,GPP_F,col=TA))+
  geom_line(aes(PPFD_IN,fit),col='red')

ggplot(data = gs)+
  geom_point(aes(PPFD_IN,FC,col=TA))+
  geom_line(aes(PPFD_IN,-fit),col='red')
```


```{r}
gs = df[complete.cases(df$PPFD_IN),]
gs = gs[complete.cases(gs$FC),]

lr = light.response(data = gs,NEE = 'FC',Reco = 'RECO',PPFD = 'PPFD_IN',PPFD_ref = 1500)
lr
fit = lr$m$fitted()

```

```{r}
ggplot(data = df)+
  geom_point(aes(PPFD_IN,GPP_F,col=TA))+
  geom_line(aes(PPFD_IN,fit),col='red')

ggplot(data = gs)+
  geom_point(aes(PPFD_IN,FC,col=TA))+
  geom_line(aes(PPFD_IN,-fit),col='red')
```
#Don't understand this code, need some explanation 

#−NEE = αPPFD/(1−(PPFD/PPFDref)+αPPFD/GPPref)−Reco
```{r}
α = 0.007827
PPFDref = 1500
GPPref = 3.225959

lr.line = predict(lr)

plot(lr.line)
fit = lr$m$fitted()

lr$
ggplot(data = gs)+
  geom_point(aes(PPFD_IN,FC,col=TA))+
  geom_smooth(formula = y ~ α*x / (1−(x/PPFDref) + α*x/GPPref) - RECO)



#Won't plot correctly, can't find "RECO" though it's in the gs df 
ggplot(data = gs) +
  geom_point(aes(x = PPFD_IN, y = FC, color = TA)) +
  geom_smooth(aes(x = PPFD_IN, y = FC), method = "lm", formula = y ~ α * x / (1 - (x / PPFDref) + α * x / GPPref) - RECO)
```



