---
title: "Alt Methane Model budgets" #examining C budgets with these diferent methane models 
output: html_document
date: "2025-01-22"
---
```{r}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, include=FALSE}
rm(list = ls())

library(data.table)
library(ggplot2)
library(cowplot)
library(openair)
library(plotrix)
library(signal)
library(svMisc)
library(zoo)
library(stringr)
library(plyr)
library(viridis)
library(lubridate)
library(tidyverse)
library(gridExtra)
library(plotly)
library(RColorBrewer)
library(pracma)
library(dplyr)


Sys.setenv(TZ='UTC')
```

# Set working directory and then Load data

TO DO: re-running all these with SWC_3 (tussock) version of dataset - KK 1/7/2025 **use the era dataset** 
```{r}
df = fread(input ="C:/Users/kkent/Documents/Council Data/Council BASE gapfilling/council_HH_alt_methane_models.csv", na.strings = "-9999")



```















#Budgets based on XGBoost model with interaction effect 

####Yearly df 
```{r}
df_2017 <- df %>%
  filter(year(date) == 2017)

df_2018 <- df %>%
  filter(year(date) == 2018)

df_2019 <- df %>%
  filter(year(date) == 2019)

df_2020 <- df %>%
  filter(year(date) == 2020)

df_2021 <- df %>%
  filter(year(date) == 2021)

df_2022 <- df %>%
  filter(year(date) == 2022)

df_2023 <- df %>%
  filter(year(date) == 2023)

```


####Annual budgets
#### Net C Budgets: Annual bar plot
```{r}
#Creates numeric timestamp with the unit of minutes to integrate over half-hourly data

#this references the half hourly increments and takes the diff (so 30 min increments)
df_2023 <- df_2023 %>%
  mutate(time_minutes = as.numeric(difftime(TIMESTAMP, min(TIMESTAMP), units = "mins")))
df_2023$TIMESTAMP

# Units start as micro-moles of CO2/(m^2/s), converted to Grams of C/m^2/minute, integrated over minutes to get Grams of C/m^2

#creating new column of net C budget in order to make the annual budget bar plots
#net CO2 
df_2023 <- df_2023 %>%
  mutate(FC_F_no_NAs = ifelse(is.na(FC_F), 0, FC_F * 60 * (1/1000000) * 12))

#Net CO2 flux in g/m2
net_CO2 <- trapz(df_2023$time_minutes, df_2023$FC_F_no_NAs)

# Units start as nano-moles of CH4/(m^2/s), converted to Grams of C/m^2/minute, integrated over minutes to get Grams of C/m^2

#Net CH4 Flux
df_2023 <- df_2023 %>%
  mutate(FCH4_F_no_NAs = ifelse(is.na(FCH4_F), 0, FCH4_F*60*(1/1000000000)*12))


net_CH4 <- trapz(df_2023$time_minutes, df_2023$FCH4_F_no_NAs)

# Used IPCC Sixth Assessment Report (AR6) global warming potentials, 100 year time period - could use paper gwp* or delta equation for future analysis

net_CH4_CO2e <- net_CH4*27.2
sum = net_CO2+net_CH4


#Dataframe created to generate bar graph
net_wp_2023 <- data.frame(
  Category = c("CO2", "CH4", "Total"),
  Value = c(round(net_CO2, 2), round(net_CH4, 2), round(sum, 2) 
))

#Plot here

annual_Cbudget_2023 <- ggplot(net_wp_2023, aes(x = Category, y = Value)) +
  theme_bw()+
  geom_bar(stat = "identity", position = "dodge", fill = "turquoise3") +
  geom_hline(yintercept=0, colour = "black")+
  labs(
    x = "",
    #y = expression(FCH4~(gCH[4]-C/m^2/s)),
    y = expression(Net~Carbon~Flux~(gC~m^-2~y^-1))) +
  geom_label(aes(label = Value), vjust = ifelse(net_wp_2023$Value >= 0, -0.7, 1.5), colour = "black", fill ="white")+
  scale_y_continuous(
     #breaks = seq(-5, 5, 1.5),  # changing for 2023 
   # limits = c(-2, 5))+ #changing for year 2023
      breaks = seq(-80, 20, 10),  # Set limits for the primary axis - other years go up to -73
    limits = c(-80, 50))+ 
  labs(title = "Cumulative Annual Carbon Budget for 2023") +#for 2023
#labs(title = "2023")
   theme(
    axis.title.x = element_text(size = 16, face = "bold"),  # Make x-axis title larger and bold
    axis.title.y = element_text(size = 16, face = "bold"),  # Make y-axis title larger and bold
    axis.text.x = element_text(size = 14, face = "bold"),   # Make x-axis text larger and bold
    axis.text.y = element_text(size = 14, face = "bold")    # Make y-axis text larger and bold
  )# +
  
#coord_fixed(ratio = 0.6) #for making small 2023 fig 

annual_Cbudget_2023

```





